// Code generated by Kitex v0.12.1. DO NOT EDIT.
package gateway

import (
	server "github.com/cloudwego/kitex/server"
	gateway "zhamghaoran/ddbr-gateway/kitex_gen/ddbr/rpc/gateway"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler gateway.Gateway, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler gateway.Gateway, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
